/* 
 * CNXT-Connector
 *
 * The CNXT-Connector is developed by Rodenstock GmbH to integrate data from measurement devices such as DNEye<sup>®</sup> Scanner, Rodenstock Fundus Scanner, and ImpressionIST<sup>®</sup> into 3rd party applications as well as into several applications of Rodenstock such as WinFit, Rodenstock Consulting etc. If you have any feedback then please feel free to contact us via email. Copyright © Rodenstock GmbH 2020
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cnxt@rodenstock.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = CNXT.Connector.Client.Client.OpenAPIDateConverter;

namespace CNXT.Connector.Client.Model
{
    /// <summary>
    /// State of the session
    /// </summary>
    /// <value>State of the session</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum SessionState
    {
        /// <summary>
        /// Enum CLOSED for value: CLOSED
        /// </summary>
        [EnumMember(Value = "CLOSED")]
        CLOSED = 1,

        /// <summary>
        /// Enum OPEN for value: OPEN
        /// </summary>
        [EnumMember(Value = "OPEN")]
        OPEN = 2,

        /// <summary>
        /// Enum ORDERED for value: ORDERED
        /// </summary>
        [EnumMember(Value = "ORDERED")]
        ORDERED = 3,

        /// <summary>
        /// Enum EXPORTED for value: EXPORTED
        /// </summary>
        [EnumMember(Value = "EXPORTED")]
        EXPORTED = 4,

        /// <summary>
        /// Enum SAVED for value: SAVED
        /// </summary>
        [EnumMember(Value = "SAVED")]
        SAVED = 5

    }

}
