/*
 * CNXT-API
 *
 * The CNXT-API is developed by Rodenstock GmbH to integrate data from measurement devices such as DNEye<sup>®</sup> Scanner, Rodenstock Fundus Scanner, and ImpressionIST<sup>®</sup> into 3rd party applications as well as into several applications of Rodenstock such as WinFit, Rodenstock Consulting etc. If you have any feedback then please feel free to contact us via email. Copyright © Rodenstock GmbH 2022
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: cnxt@rodenstock.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNXT.Connector.Client.Api;
using CNXT.Connector.Client.Model;
using CNXT.Connector.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CNXT.Connector.Client.Test
{
    /// <summary>
    ///  Class for testing B2BOptic
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class B2BOpticTests
    {
        // TODO uncomment below to declare an instance variable for B2BOptic
        //private B2BOptic instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of B2BOptic
            //instance = new B2BOptic();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of B2BOptic
        /// </summary>
        [Test]
        public void B2BOpticInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" B2BOptic
            //Assert.IsInstanceOf(typeof(B2BOptic), instance);
        }


        /// <summary>
        /// Test the property 'Xml'
        /// </summary>
        [Test]
        public void XmlTest()
        {
            // TODO unit test for the property 'Xml'
        }
        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Test]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }

    }

}
