/* 
 * CNXT®-Connector
 *
 * The CNXT<sup>®</sup>-Connector is developed by Rodenstock GmbH to integrate data from measurement devices such as DNEye<sup>®</sup> Scanner, Rodenstock Fundus Scanner, and ImpressionIST<sup>®</sup> into 3rd party applications as well as into several applications of Rodenstock such as WinFit, Rodenstock Consulting etc. If you have any feedback then please feel free to contact us via email. Copyright © Rodenstock GmbH 2020
 *
 * The version of the OpenAPI document: 1.0.5
 * Contact: cnxt@rodenstock.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNXT.Connector.Client.Api;
using CNXT.Connector.Client.Model;
using CNXT.Connector.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CNXT.Connector.Client.Test
{
    /// <summary>
    ///  Class for testing PageInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PageInfoTests
    {
        // TODO uncomment below to declare an instance variable for PageInfo
        //private PageInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PageInfo
            //instance = new PageInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PageInfo
        /// </summary>
        [Test]
        public void PageInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PageInfo
            //Assert.IsInstanceOf(typeof(PageInfo), instance);
        }


        /// <summary>
        /// Test the property 'HasPreviousPage'
        /// </summary>
        [Test]
        public void HasPreviousPageTest()
        {
            // TODO unit test for the property 'HasPreviousPage'
        }
        /// <summary>
        /// Test the property 'HasNextPage'
        /// </summary>
        [Test]
        public void HasNextPageTest()
        {
            // TODO unit test for the property 'HasNextPage'
        }
        /// <summary>
        /// Test the property 'StartCursor'
        /// </summary>
        [Test]
        public void StartCursorTest()
        {
            // TODO unit test for the property 'StartCursor'
        }
        /// <summary>
        /// Test the property 'EndCursor'
        /// </summary>
        [Test]
        public void EndCursorTest()
        {
            // TODO unit test for the property 'EndCursor'
        }

    }

}
