/* 
 * CNXT-Connector
 *
 * The CNXT-Connector is developed by Rodenstock GmbH to integrate data from measurement devices such as DNEye<sup>®</sup> Scanner, Rodenstock Fundus Scanner, and ImpressionIST<sup>®</sup> into 3rd party applications as well as into several applications of Rodenstock such as WinFit, Rodenstock Consulting etc. If you have any feedback then please feel free to contact us via email. Copyright © Rodenstock GmbH 2020
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: cnxt@rodenstock.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNXT.Connector.Client.Api;
using CNXT.Connector.Client.Model;
using CNXT.Connector.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CNXT.Connector.Client.Test
{
    /// <summary>
    ///  Class for testing PatientFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatientFilterTests
    {
        // TODO uncomment below to declare an instance variable for PatientFilter
        //private PatientFilter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatientFilter
            //instance = new PatientFilter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatientFilter
        /// </summary>
        [Test]
        public void PatientFilterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PatientFilter
            //Assert.IsInstanceOf(typeof(PatientFilter), instance);
        }


        /// <summary>
        /// Test the property 'Search'
        /// </summary>
        [Test]
        public void SearchTest()
        {
            // TODO unit test for the property 'Search'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Test]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'SessionUpdatedAfter'
        /// </summary>
        [Test]
        public void SessionUpdatedAfterTest()
        {
            // TODO unit test for the property 'SessionUpdatedAfter'
        }
        /// <summary>
        /// Test the property 'CreatedAfter'
        /// </summary>
        [Test]
        public void CreatedAfterTest()
        {
            // TODO unit test for the property 'CreatedAfter'
        }
        /// <summary>
        /// Test the property 'UpdatedAfter'
        /// </summary>
        [Test]
        public void UpdatedAfterTest()
        {
            // TODO unit test for the property 'UpdatedAfter'
        }

    }

}
