/*
 * CNXT-API
 *
 * The CNXT-API is developed by Rodenstock GmbH to integrate data from measurement devices such as DNEye<sup>®</sup> Scanner, Rodenstock Fundus Scanner, and ImpressionIST<sup>®</sup> into 3rd party applications as well as into several applications of Rodenstock such as WinFit, Rodenstock Consulting etc. If you have any feedback then please feel free to contact us via email. Copyright © Rodenstock GmbH 2022
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: cnxt@rodenstock.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNXT.Connector.Client.Api;
using CNXT.Connector.Client.Model;
using CNXT.Connector.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CNXT.Connector.Client.Test
{
    /// <summary>
    ///  Class for testing PatientLinkSessionsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatientLinkSessionsInnerTests
    {
        // TODO uncomment below to declare an instance variable for PatientLinkSessionsInner
        //private PatientLinkSessionsInner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PatientLinkSessionsInner
            //instance = new PatientLinkSessionsInner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PatientLinkSessionsInner
        /// </summary>
        [Test]
        public void PatientLinkSessionsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" PatientLinkSessionsInner
            //Assert.IsInstanceOf(typeof(PatientLinkSessionsInner), instance);
        }


        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }

    }

}
