/*
 * CNXT-API
 *
 * The CNXT-API is developed by Rodenstock GmbH to integrate data from measurement devices such as DNEye<sup>®</sup> Scanner, Rodenstock Fundus Scanner, and ImpressionIST<sup>®</sup> into 3rd party applications as well as into several applications of Rodenstock such as WinFit, Rodenstock Consulting etc. If you have any feedback then please feel free to contact us via email. Copyright © Rodenstock GmbH 2022
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: cnxt@rodenstock.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using CNXT.Connector.Client.Api;
using CNXT.Connector.Client.Model;
using CNXT.Connector.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace CNXT.Connector.Client.Test
{
    /// <summary>
    ///  Class for testing SessionFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionFilterTests
    {
        // TODO uncomment below to declare an instance variable for SessionFilter
        //private SessionFilter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SessionFilter
            //instance = new SessionFilter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SessionFilter
        /// </summary>
        [Test]
        public void SessionFilterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SessionFilter
            //Assert.IsInstanceOf(typeof(SessionFilter), instance);
        }


        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'PatientId'
        /// </summary>
        [Test]
        public void PatientIdTest()
        {
            // TODO unit test for the property 'PatientId'
        }
        /// <summary>
        /// Test the property 'CreatedAfter'
        /// </summary>
        [Test]
        public void CreatedAfterTest()
        {
            // TODO unit test for the property 'CreatedAfter'
        }
        /// <summary>
        /// Test the property 'UpdatedAfter'
        /// </summary>
        [Test]
        public void UpdatedAfterTest()
        {
            // TODO unit test for the property 'UpdatedAfter'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'HasDNEyeData'
        /// </summary>
        [Test]
        public void HasDNEyeDataTest()
        {
            // TODO unit test for the property 'HasDNEyeData'
        }
        /// <summary>
        /// Test the property 'HasImpressionISTData'
        /// </summary>
        [Test]
        public void HasImpressionISTDataTest()
        {
            // TODO unit test for the property 'HasImpressionISTData'
        }
        /// <summary>
        /// Test the property 'HasRxData'
        /// </summary>
        [Test]
        public void HasRxDataTest()
        {
            // TODO unit test for the property 'HasRxData'
        }

    }

}
